import type { AboutInfo, Project, Skill, Testimonial, Experience } from "@shared";

export const DUMMY_ABOUT: AboutInfo = {
  id: "dummy-about",
  name: "Sahil R. Sharma",
  title: "Full-Stack Engineer · 3D Web Specialist",
  bio: "I build production-grade web platforms with React, Node and WebGL. Brutalist by design, type-safe by default. Ten years shipping for startups, agencies and Fortune 500 brands.",
  avatarUrl: null,
  resumeUrl: "#",
  email: "hello@codebysrs.dev",
  phone: "+1 (555) 010-2026",
  location: "Berlin · Remote-first",
  githubUrl: "https://github.com/codebysrs",
  linkedinUrl: "https://linkedin.com/in/codebysrs",
  twitterUrl: "https://twitter.com/codebysrs",
  instagramUrl: "https://instagram.com/codebysrs",
  availableForWork: true,
  responseTime: "< 24h",
  workingHours: "09:00 – 18:00 CET",
  completedProjects: 87,
  totalClients: 42,
  yearsExperience: 10,
  technologiesCount: 36,
  createdAt: new Date(),
  updatedAt: new Date(),
} as unknown as AboutInfo;

export const DUMMY_PROJECTS: Project[] = [
  {
    id: "p-001",
    title: "Atlas Configurator",
    description:
      "Real-time 3D product configurator for an industrial OEM. Three.js + React + Vercel Edge.",
    imageUrl: null,
    technologies: ["React", "Three.js", "WebGL", "Vercel Edge", "TypeScript"],
    githubUrl: "#",
    liveUrl: "#",
    featured: true,
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "p-002",
    title: "Numen CMS",
    description:
      "Headless CMS for a media network. PostgreSQL, Drizzle ORM, fine-grained RBAC.",
    imageUrl: null,
    technologies: ["Next.js", "Postgres", "Drizzle", "Trpc"],
    githubUrl: "#",
    liveUrl: "#",
    featured: true,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "p-003",
    title: "Voltline Dashboard",
    description:
      "Realtime energy telemetry dashboard. WebSockets, sub-second charting, dark-only UI.",
    imageUrl: null,
    technologies: ["React", "WebSockets", "D3", "Tailwind"],
    githubUrl: "#",
    liveUrl: "#",
    featured: true,
    order: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "p-004",
    title: "Klein Bottles",
    description:
      "E-commerce for a craft brewery. Headless Shopify, custom checkout, +38% conversion.",
    imageUrl: null,
    technologies: ["Shopify", "Hydrogen", "Remix", "Stripe"],
    githubUrl: "#",
    liveUrl: "#",
    featured: true,
    order: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "p-005",
    title: "Fieldnote",
    description:
      "Offline-first PWA for field researchers. Sync engine, conflict resolution, IndexedDB.",
    imageUrl: null,
    technologies: ["PWA", "IndexedDB", "Service Worker", "React"],
    githubUrl: "#",
    liveUrl: "#",
    featured: true,
    order: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "p-006",
    title: "Orbital Studio",
    description:
      "Marketing site for a motion design studio. WebGL hero, 100/100 Lighthouse.",
    imageUrl: null,
    technologies: ["Astro", "Three.js", "GSAP", "Cloudflare"],
    githubUrl: "#",
    liveUrl: "#",
    featured: true,
    order: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const DUMMY_SKILLS: Skill[] = [
  // Frontend
  { id: "s-1", name: "React", category: "Frontend", proficiency: 96, order: 1, icon: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "s-2", name: "TypeScript", category: "Frontend", proficiency: 94, order: 2, icon: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "s-3", name: "Next.js", category: "Frontend", proficiency: 90, order: 3, icon: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "s-4", name: "Tailwind CSS", category: "Frontend", proficiency: 92, order: 4, icon: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "s-5", name: "Framer Motion", category: "Frontend", proficiency: 84, order: 5, icon: null, createdAt: new Date(), updatedAt: new Date() },
  // Backend
  { id: "s-6", name: "Node.js", category: "Backend", proficiency: 91, order: 1, icon: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "s-7", name: "PostgreSQL", category: "Backend", proficiency: 88, order: 2, icon: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "s-8", name: "Drizzle ORM", category: "Backend", proficiency: 85, order: 3, icon: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "s-9", name: "Redis", category: "Backend", proficiency: 78, order: 4, icon: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "s-10", name: "GraphQL", category: "Backend", proficiency: 80, order: 5, icon: null, createdAt: new Date(), updatedAt: new Date() },
  // 3D / Graphics
  { id: "s-11", name: "Three.js", category: "3D/Graphics", proficiency: 87, order: 1, icon: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "s-12", name: "WebGL / GLSL", category: "3D/Graphics", proficiency: 78, order: 2, icon: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "s-13", name: "GSAP", category: "3D/Graphics", proficiency: 82, order: 3, icon: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "s-14", name: "Blender", category: "3D/Graphics", proficiency: 65, order: 4, icon: null, createdAt: new Date(), updatedAt: new Date() },
  // Tools
  { id: "s-15", name: "Vite", category: "Tools", proficiency: 92, order: 1, icon: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "s-16", name: "Docker", category: "Tools", proficiency: 81, order: 2, icon: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "s-17", name: "GitHub Actions", category: "Tools", proficiency: 86, order: 3, icon: null, createdAt: new Date(), updatedAt: new Date() },
  { id: "s-18", name: "Figma", category: "Tools", proficiency: 79, order: 4, icon: null, createdAt: new Date(), updatedAt: new Date() },
] as unknown as Skill[];

export const DUMMY_EXPERIENCE: Experience[] = [
  {
    id: "e-001",
    role: "Senior Full Stack Engineer",
    company: "Tech Corp",
    type: "JOB",
    startYear: 2021,
    endYear: 2024,
    description: "Led frontend architecture and built scalable React applications. Mentored junior developers and drove performance optimizations across the stack.",
    order: 1,
    createdAt: new Date(),
  },
  {
    id: "e-002",
    role: "Freelance Creative Developer",
    company: "Self",
    type: "FREELANCE",
    startYear: 2019,
    endYear: 2021,
    description: "Built custom websites and immersive WebGL experiences for startups and agencies worldwide. Full-stack delivery from brief to production.",
    order: 2,
    createdAt: new Date(),
  },
  {
    id: "e-003",
    role: "Frontend Engineer",
    company: "Web Agency",
    type: "JOB",
    startYear: 2017,
    endYear: 2019,
    description: "Developed pixel-perfect React interfaces and design systems. Collaborated directly with design teams to ship brand-consistent products.",
    order: 3,
    createdAt: new Date(),
  },
  {
    id: "e-004",
    role: "Junior Developer",
    company: "StartUp XYZ",
    type: "JOB",
    startYear: 2015,
    endYear: 2017,
    description: "Full-stack development with JavaScript and Node.js. Built REST APIs and interactive dashboards for B2B SaaS clients.",
    order: 4,
    createdAt: new Date(),
  },
] as unknown as Experience[];

export const DUMMY_TESTIMONIALS: Testimonial[] = [
  {
    id: "t-1",
    name: "Lena Kohler",
    role: "VP Product",
    company: "Helix Labs",
    content:
      "Sahil rebuilt our checkout in three weeks. Conversion went up 22% and the codebase is finally something we enjoy working in.",
    rating: 5,
    avatarUrl: null,
    isVisible: true,
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "t-2",
    name: "Marcus Tan",
    role: "CTO",
    company: "Voltline",
    content:
      "Brutally clear communicator. Shipped a real-time dashboard our ops team uses every single shift. No drama, just delivery.",
    rating: 5,
    avatarUrl: null,
    isVisible: true,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "t-3",
    name: "Priya Raman",
    role: "Founder",
    company: "Fieldnote",
    content:
      "Hired Sahil to consult, ended up shipping the whole MVP with him. Type-safe end-to-end and faster than any team I've worked with.",
    rating: 5,
    avatarUrl: null,
    isVisible: true,
    order: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "t-4",
    name: "Tomáš Novák",
    role: "Design Lead",
    company: "Orbital Studio",
    content:
      "Pixel-perfect handoffs with WebGL flair. He cares about motion the same way good designers care about typography.",
    rating: 5,
    avatarUrl: null,
    isVisible: true,
    order: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "t-5",
    name: "Aisha Bello",
    role: "Engineering Manager",
    company: "Numen Media",
    content:
      "Architected our headless CMS with patience and rigor. PRs came with diagrams. Onboarding new engineers is now a non-event.",
    rating: 5,
    avatarUrl: null,
    isVisible: true,
    order: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "t-6",
    name: "Jonas Weber",
    role: "Head of Growth",
    company: "Klein Brewing",
    content:
      "We asked for a marketing site and got a revenue engine. The brutalist art direction is now the centrepiece of the brand.",
    rating: 5,
    avatarUrl: null,
    isVisible: true,
    order: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
] as unknown as Testimonial[];
