// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/skills-variants/BentoGrid.tsx": () => import("../components/mockups/skills-variants/BentoGrid.tsx"),
  "./components/mockups/skills-variants/DiagnosticRows.tsx": () => import("../components/mockups/skills-variants/DiagnosticRows.tsx"),
  "./components/mockups/skills-variants/MarqueeStack.tsx": () => import("../components/mockups/skills-variants/MarqueeStack.tsx")
};
